services:

  web:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://pg:pgpass@trackable-db-1:5432/trackable"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: ""
      GOOGLE_CLIENT_ID: ""
      GOOGLE_CLIENT_SECRET: ""
    command: ./docker-entrypoint.sh

  db:
    image: postgres:18
    restart: always
    ports:
      - 5433:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pg
      POSTGRES_DB: trackable
    volumes:
      - datavol:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  datavol:


