services:

  web:
    build: .
    restart: always
    ports:
      - 3000:3000
    command: ./docker-entrypoint.sh

  db:
    image: postgres:18
    restart: always
    ports:
      - 5433:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pg
      POSTGRES_DB: trackable
    volumes:
      - datavol:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  datavol:


